# Configuration for the WebLogic Domain
---

# Need mainly user and password filled in
# Will figure out domain name and server name based on application name from VCAP_APPLICATION Env variable
#

Domain:
  wlsUser: weblogic
  wlsPasswd: welcome1
  consoleEnabled: true
  prodModeEnabled: false
