# Configuration for the WebLogic Server JVM
---

# All JVM parameters specified default to MB
JVM:
  # For optimal performance, set min and max perm size to same value
  # for large apps with lots of classes/jsp etc., bump to 512 or 1024m
  minPerm: 256
  maxPerm: 256
  #maxPermSize: 512
  # For optimal perf, set min and max heap size to same value
  # For large apps, bump to 1024 or 2048 MB (depending on the quota..)
  minHeap: 512
  maxHeap: 1024
  otherJvmOpts: -verbose:gc -Xloggc:gc.log -XX:+PrintGCDetails -XX:+PrintGCTimeStamps  -XX:+HeapDumpOnOutOfMemoryError


